// setting.js

document.addEventListener("DOMContentLoaded", function () {
});
function storeValue() {
    let firstname = document.getElementById("fullNameFirst").value;
    let middlename = document.getElementById("middleNameFirst").value;
    let lastname = document.getElementById("lastNameFirst").value;
    let firstnamealt = document.getElementById("fullNamealt").value;
    let middlenamealt = document.getElementById("middleNamealt").value;
    let lastnamealt = document.getElementById("lastNamealt").value;
    let permanentStreet = document.getElementById("street").value;
    let permanentWard = document.getElementById("ward").value;
    let permanentMunicipality = document.getElementById("municipality").value;
    let permanentDistrict = document.getElementById("district").value;
    let permanentprovince = document.getElementById("province").value;
    let permanentcountry = document.getElementById("country").value;
    let temporaryStreet = document.getElementById("streetTemp").value;
    let temporaryWard = document.getElementById("wardTemp").value;
    let temporaryMunicipality = document.getElementById("municipalityTemp").value;
    let temporaryDistrict = document.getElementById("tempDistrict").value;
    let temporaryprovince = document.getElementById("provinceTemp").value;
    let temporarycountry = document.getElementById("countryTemp").value;
    let dateOfBirth = document.getElementById("dateOfBirth").value;
    let gender = document.getElementById("gender").value;
    let maritalStatus = document.getElementById("maritalStatus").value;
    let gmail = document.getElementById("gmail").value;
    let phoneNumber = document.getElementById("phoneNumber").value;
    let passportNumber = document.getElementById("passportNumber").value;
    let issuedCountry = document.getElementById("passIssueCountry").value;
    let issuedDistrict = document.getElementById("issuedDistrict").value;
    let dateOfIssue = document.getElementById("dateOfIssuePass").value;
    let dateofExpiry = document.getElementById("dateOfExpiryPass").value;
    let countryForApplication = document.getElementById("CountryForapplication").value;
    let Forapplication = document.getElementById("Forapplication").value;
    let boardForapplication = document.getElementById("boardForapplication").value;
    let primarySchool = document.getElementById("primarySchoolName").value;
    let primarySchoolAddress = document.getElementById("primarySchoolAddress").value;
    let primaryStartedDate = document.getElementById("primaryStartedDate").value;
    let primarycompletionDate = document.getElementById("primaryCompletionDate").value;
    let secondarySchool = document.getElementById("secondarySchoolName").value;
    let secondarySchoolAddress = document.getElementById("secondarySchoolAddress").value;
    let secondaryStartedDate = document.getElementById("secondaryStartedDate").value;
    let secondarycompletionDate = document.getElementById("secondaryCompletionDate").value;
    let higherSchool = document.getElementById("higherSchool").value;
    let higherSchoolAddress = document.getElementById("higherAddress").value;
    let higherStartedDate = document.getElementById("higherStartedDate").value;
    let highercompletionDate = document.getElementById("higherCompletionDate").value;
    let pclSchoolName = document.getElementById("pclSchoolName").value;
    let pclSchoolAddress = document.getElementById("pclSchoolAddress").value;
    let pclDateOfStarted = document.getElementById("pclDateOfStarted").value;
    let pclDateOfCompletion = document.getElementById("pclDateOfCompletion").value;
    let bnbscSchoolName = document.getElementById("bn/bscSchoolName").value;
    let bnbscSchoolAddress = document.getElementById("bn/bscSchoolAddress").value;
    let bnbscDateOfStarted = document.getElementById("bn/bscDateOfStarted").value;
    let bnbscDateOfCompletion = document.getElementById("bn/bscDateOfCompletion").value;
    let nncRegdNo = document.getElementById("nncRegistrationNumber").value;
    let nncExamDate = document.getElementById("nncExamDate").value;
    let nncRegistrationDate = document.getElementById("nncRegistrationDate").value;
    let nncExpiryDate = document.getElementById("nncExpiryDate").value;
    let multipleExam = document.querySelector('input[name="exam"]:checked').value;
    let noOfattempts = document.getElementById("noOfAttempts").value;
    let jobTitle = document.getElementById("jobTitle").value;
    let hospitalName = document.getElementById("jobHospitalName").value;
    let hospitalPermanentAddress = document.getElementById("jobHospitalAddress").value;
    let supervisiorName = document.getElementById("jobSupervisiorName").value;
    let supervisiorPosition = document.getElementById("jobSupervisiorPost").value;
    let dateOfStarted = document.getElementById("jobDateOfStarted").value;
    let dateOfCompletion = document.getElementById("jobDateOfCompletion").value;
    let langTest = document.getElementById("langTest").value;
    let langTestDate = document.getElementById("langTestDate").value;
    let langTestMarks = document.getElementById("langTestMarks").value;
    let guardianName = document.getElementById("guardianName").value;
    let relation = document.getElementById("guardianRelation").value;
    let guardianAddress = document.getElementById("guardianAddress").value;
    let guardianContact = document.getElementById("guardianContact").value;
    let guardianOccupation = document.getElementById("guardianOccupation").value;



    localStorage.setItem('storedFullNameFirst', firstname);
    localStorage.setItem('storedMiddleNameFirst', middlename);
    localStorage.setItem('storedLastNameFirst', lastname);
    localStorage.setItem('storedAltNameFirst', firstnamealt);
    localStorage.setItem('storedAltNameMiddle', middlenamealt);
    localStorage.setItem('storedAltNameLast', lastnamealt);
    localStorage.setItem('storedPermastreet', permanentStreet);
    localStorage.setItem('storedPermaward', permanentWard);
    localStorage.setItem('storedPermaMunicipality', permanentMunicipality);
    localStorage.setItem('storedPermadistrict', permanentDistrict);
    localStorage.setItem('storedPermaProvi', permanentprovince);
    localStorage.setItem('storedPermaCont', permanentcountry);
    localStorage.setItem('storedTempStreet', temporaryStreet);
    localStorage.setItem('storedTempWard', temporaryWard);
    localStorage.setItem('storedTempmunic', temporaryMunicipality);
    localStorage.setItem('storedTempDistrict', temporaryDistrict);
    localStorage.setItem('storedTempProvit', temporaryprovince);
    localStorage.setItem('storedTempCont', temporarycountry);
    localStorage.setItem('storedDateOfBirth', dateOfBirth);
    localStorage.setItem('storedGender', gender);
    localStorage.setItem('storedMaritalSatus', maritalStatus);
    localStorage.setItem('storedGmail', gmail);
    localStorage.setItem('storedNumber', phoneNumber);
    localStorage.setItem('storedPassNumber', passportNumber);
    localStorage.setItem('storedIssueContry', issuedCountry);
    localStorage.setItem('storedIssueDis', issuedDistrict);
    localStorage.setItem('storedIssueDate', dateOfIssue);
    localStorage.setItem('storedIssueExpiry', dateofExpiry);
    localStorage.setItem('storedConForApp', countryForApplication);
    localStorage.setItem('storedForApp', Forapplication);
    localStorage.setItem('storedBoardOfApp', boardForapplication);
    localStorage.setItem('storedPrimeName', primarySchool);
    localStorage.setItem('storedPrimeSclAdd', primarySchoolAddress);
    localStorage.setItem('storedPrimeStart', primaryStartedDate);
    localStorage.setItem('storedPrimeComp', primarycompletionDate);
    localStorage.setItem('storedSecName', secondarySchool);
    localStorage.setItem('storedSecAdd', secondarySchoolAddress);
    localStorage.setItem('storedSecStart', secondaryStartedDate);
    localStorage.setItem('storedSecComp', secondarycompletionDate);
    localStorage.setItem('storedHighScl', higherSchool);
    localStorage.setItem('storedHighAdd', higherSchoolAddress);
    localStorage.setItem('storedHighStart', higherStartedDate);
    localStorage.setItem('storedHighComp', highercompletionDate);
    localStorage.setItem('storedPclSclName', pclSchoolName);
    localStorage.setItem('storedPclSclAdd', pclSchoolAddress);
    localStorage.setItem('storedPclStart', pclDateOfStarted);
    localStorage.setItem('storedPclComp', pclDateOfCompletion);
    localStorage.setItem('storedBscSclName', bnbscSchoolName);
    localStorage.setItem('storedBScAdd', bnbscSchoolAddress);
    localStorage.setItem('storedBscStart', bnbscDateOfStarted);
    localStorage.setItem('storedBscComp', bnbscDateOfCompletion);
    localStorage.setItem('storedNncregd', nncRegdNo);
    localStorage.setItem('storedNncExamDate', nncExamDate);
    localStorage.setItem('storedNncRegdDate', nncRegistrationDate);
    localStorage.setItem('storedNncExpiry', nncExpiryDate);
    localStorage.setItem('storedMultipleExam', multipleExam);
    localStorage.setItem('storedNoOfAtempts', noOfattempts);
    localStorage.setItem('storedJobTitle', jobTitle);
    localStorage.setItem('storedHosName', hospitalName);
    localStorage.setItem('storedHosAdd', hospitalPermanentAddress);
    localStorage.setItem('storedSuperName', supervisiorName);
    localStorage.setItem('storedSuperPosition', supervisiorPosition);
    localStorage.setItem('storedDateOfSatrt', dateOfStarted);
    localStorage.setItem('storedDateOfComp', dateOfCompletion);
    localStorage.setItem('storedLangTest', langTest);
    localStorage.setItem('storedLangDate', langTestDate);
    localStorage.setItem('storedLangMark', langTestMarks);
    localStorage.setItem('storedGuardName', guardianName);
    localStorage.setItem('storedRelation', relation);
    localStorage.setItem('storedGuardAdd', guardianAddress);
    localStorage.setItem('storedGuardContact', guardianContact);
    localStorage.setItem('storedGuardOccup', guardianOccupation);
}

//   function setValues() {
//     window.location.href = 'displayValuesPage.html';
//   }